== Containerization ==
Docker is the standard container technology supported by Kubernetes and provides the basis for standardized
application deployments.
However, from a microservice DevOps team perspective, dealing with Docker does not add any value to the
application from an end-user perspective. The idea is therefore to hide the container technology from the normal
developer or DevOps teams and at the same time keep the flexibility to explore new technologies, which might
require a completely different container setup than for the existing technologies. Such prototyping applications
will probably not be supported in the same way as the established technology stacks at first, which means there
is more effort to deploy and operate them. But as the best-practices for the new technology are shaping up, a
blueprint for those applications can be created and thus be supported by the platform as well.

The following stacks are quite popular in the enterprise world today:

* Java
** Jakarta EE (e.g. WebSphere Liberty Profile)
** Spring Boot
* NodeJS
* .NET
* ...

For those common technology stacks, the platform must provide a DevOps experience where it is easy to deploy new
business functionality into production without the need to deal with low-level Docker or Kubernetes.


=== Configuration ===
Each technology requires different hooks into the container creation process. For example, in Java the max heap
settings must be configured by the team that is responsible for the microservice, when following a DevOps approach.
Additional properties are:

* wait time for becoming ready, i.e. when is application ready to serve requests (readiness in Kubernetes)
** initial delay
** frequency of probe
* liveness defines whether the application is able to serve requests, i.e. health status
** initial delay
** frequency of probe
* heap settings
* truststore/keystore
* network proxy settings
* other vm parameters or environment variables

See https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html[Cloud Foundry's manifest.mf]
file as an example for which aspects of an application must be configurable.


=== Conventions ===
With Docker the TCP port of a microservice is not an issue to be discovered anymore (see chapter on containerization).
By using conventions, each microservice starts its HTTP endpoint at port 80, its HTTPS port at 443, and if
Hazelcast is involved, the Hazelcast cluster port 5701 will be used. Each application lives in a different
container and thus can use the full range of TCP ports.

WARNING: TODO: How to work with multiple microservices locally on a developer machine when all use the same port?
Random port?


=== Java ===
Docker is supported natively in Java 10 and higher. For Java 8 and Java 9 VMs the support has been backported, but
needs to be activated explicitly (See https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits[Support for Docker CPU and Memory Limits])
Ideally the next Long Term Support version Java 11 should be used to not worry about Java in Docker anymore.


==== Spring Boot ====
Spring Boot applications are quite easy to containerize, see https://spring.io/guides/gs/spring-boot-docker/[Spring Boot with Docker]
for an example.

In a Spring Boot application the Actuator health endpoint can be used for readiness and liveness probing. This
should be the default setting. If an application choses to have a special readiness implementation then it must be
possible for the application to override the default. An example for this might be an application that does
some cache warm up after it starts. The Spring Boot application has started its web container and the health
endpoints returns 200 OK because the database can be reached and there is enough space on the file-system.
As a last step in the application startup phase it starts populating the cache with entries which might take a
few minutes to adapt.

One possibility to implement this would be to provide a different endpoint, e.g. `/readiness` which calls the
HealthIndicator as a default, which is also executed by the `/health` endpoint. When an application has the need for
a special readiness implementation it could override the `ReadinessIndicator` and implement a custom logic there.


==== WebSphere Liberty profile (Jakarta EE) ====
For WebSphere liberty profile there are pre-built images available from IBM, see
https://store.docker.com/images/websphere-liberty[IBM WebSphere Application Server Liberty] on Docker Hub.


=== Build Process ===
The build process takes the latest available Java Docker base image and creates an application specific image
on top of it. It must be possible to trigger this process outside of the application deployment or release process to
be able to update the application images by using a new Java base images in case of any security issues.

TODO: See Helm and Draft on how to build K8s packages


=== Open Issues ===
The following issues need to be clarified in the context of Containerization:

*  Configuring the Readiness and Liveness probes
** http://zavyn.blogspot.de/2017/05/kubernetes-readiness-and-liveness-with.html
** https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
** Liveness is different than readiness and should only be the same as a fallback. However readiness often requires an
extra endpoint because the service might be operational, i.e. live, but not ready yet.
** Do we need an additional readiness check in Spring Boot Actuator? The Blogpost from above uses the health endpoint
for both, readiness and liveness.
* Exact definition of the build process => Use helm.sh and draft.sh for deploying applications
* How to make sure that microservices can easily be used locally without forcing them to run minikube
