== Containerization ==
Docker is the standard container technology supported by Kubernetes and provides the basis for a standardized
application deployment.
However, from a microservice DevOps team perspective, dealing with Docker does not add any value to the
application from an end-user perspective. The idea is therefore to hide the container technology from the normal
developer or DevOps teams and at the same time keep the flexibility to explore new technologies, which might
require a completely different container setup than for the existing technologies. Such explorative applications
will probably not be supported in the same way as the established technology stacks.

The following stacks are quite popular in enterprises today:

* Java
** Jakarta EE (e.g. WebSphere Liberty Profile)
** Spring Boot
* NodeJS
* .NET
* ...

For those common technology stacks, the platform must provide a DevOps experience where it is easy to deploy new
functionality to production.

=== Configuration ===
Each technology requires different hooks into the container creation process. For example, in Java the max heap
settings must be configured by the team that is responsible for the microservice, following a DevOps approach.

TODO: All applications should follow the 12-factor approach to allow configuration via environment variables

=== Conventions ===
With Docker the TCP port of a microservice is not an issue to be discovered anymore (see chapter on containerization).
By using conventions, each microservice starts its HTTP endpoint at port 80, its HTTPS port at 443, and if
Hazelcast is involved, the Hazelcast cluster port 5701 will be used. Each application lives in a different
container and thus can use the full range of TCP ports.


=== Java ===
Docker is supported natively in Java 10 and higher. For Java 8 and Java 9 VMs the support has been backported, but
needs to be activated explicitly.

==== Spring Boot ====

Spring Boot applications are quite easy to containerize. The hooks into the container

*

==== WebSphere Liberty profile (Jakarta EE) ====




=== Open Issues ===


TODO:

*  Configuring the Readiness and Liveness probes
** http://zavyn.blogspot.de/2017/05/kubernetes-readiness-and-liveness-with.html
** https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
** Open Issues
*** Liveness is different than readiness and should only be the same as a fallback. However readiness often requires an
extra endpoint because the service might be operational, i.e. live, but not ready yet.
* Check what can be configured in Cloud Foundry's manifest.mf to derive the configuration hooks