== Load Balancing ==
Load-Balancing in Kubernetes is defined by multiple factors.
There is no load balancer in Kubernetes itself. Instead, when creating a service of type LoadBalancer, a cloud
provider's load-balancer is provisioned as the Kubernetes service. That is the reason why it is currently not
possible for Minikube to create a resource of type LoadBalancer
(see https://github.com/kubernetes/minikube/issues/384[Loadbalancer support] for a solution)

This makes the behavior of the load-balancer dependent on the cloud that is used underneath. Also in terms of
configuration, configuring an AWS' Elastic Load Balancer is completely different to configuring
load-balancers on Azure, IBM, or on the Google cloud.

Instead the client side load-balancing features are provided by Istio's Envoy proxy. That makes client side
load-balancing available to all types of applications, not only Java based Spring Boot microservices. From a Spring
Boot application perspective, the Ribbon library can be dropped completely.

=== Migration Path

. Switch to DNS based service discovery (see chapter <<Service Registration & Discovery>>)
. Disable Ribbon and let Istio step in to do client side load-balancing

=== Open Issues ===

* Which load-balancing policy should be used?
** Random
** Round-Robin
** Weighted least request (similar to response time as used by Ribbon)
