== Monitoring ==


=== Prometheus ===

There are plugins to automatically detect new services, deployed on Kubernetes and change the configuration to start scraping the metrics endpoints.

Prerequisite: Spring Boot 2.0 with Micrometer

TODO: ....

==== Migration Steps


=== OpenTracing ===
The http://opentracing.io/[OpenTracing] initiative aims at removing the vendor lock in distributed tracing.
OpenTracing is a standard for distributed tracing which is implemented by many different frameworks and tools.

A good description of why https://www.jaegertracing.io/[JaegerTracing] was created can be found in this
https://eng.uber.com/distributed-tracing/[blog]. JaegerTracing supports
https://www.jaegertracing.io/docs/client-libraries/[client libraries] in many different languages:

* Go
* Java
* JavaScript
* Python
* C++
* C#

Besides the basic client libraries, support for OpenTracing has been added into many tools and frameworks:

* https://github.com/opentracing-contrib/javascript-express[Express (NodeJS)]
* https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/tracing.html?highlight=opentracing[Envoy proxy (Istio)]
* https://github.com/opentracing-contrib/java-apache-httpclient[Apache HttpClient]
* https://github.com/opentracing-contrib/java-jdbc[PostgreSQL]
* https://github.com/opentracing-contrib/java-spring-cloud[Spring Cloud]
* https://github.com/opentracing-contrib/java-hazelcast[Hazelcast]
* https://github.com/opentracing-contrib/java-spring-web[Spring Web]
* https://github.com/opentracing-contrib/java-metrics[Java]
* https://github.com/opentracing-contrib/java-spring-messaging[Spring Messaging]
* https://github.com/opentracing-contrib/java-rabbitmq-client[Rabbit MQ]
* https://github.com/opentracing-contrib/java-grpc[gRPC]

==== Migration Steps
...


=== Open Issues
TODO

* How does all of that fit into Micrometer.io / Spring Boot 2.x changes?
